#!/usr/bin/env python3
"""
rescore_math500.py — Re-score math500_results.json with math-verify.

Reads outputs/math500_results.json (generated by math500_eval.py),
re-scores every sample with math-verify (ANTLR4/SymPy), and writes
outputs/baseline_math500_mv_rescored.json with updated scores.

This is the canonical script for producing the authoritative baseline numbers:
  - 35.8% greedy pass@1   (math-verify)
  - 65.0% pass@8          (math-verify)
  - 24.55% inferred pass@1 (c/n from pass@8 samples, math-verify)

Input:  outputs/math500_results.json
Output: outputs/baseline_math500_mv_rescored.json

Usage:
    cd /path/to/qwen3-math-rlvr
    pip install 'math-verify[antlr4_13_2]'
    python scripts/rescore_math500.py
    python scripts/rescore_math500.py --input outputs/math500_results.json
"""

import argparse
import json
import sys
from collections import defaultdict
from pathlib import Path

try:
    from math_verify import parse as mv_parse, verify as mv_verify_fn
except ImportError:
    print("ERROR: math-verify not installed.")
    print("Run: pip install 'math-verify[antlr4_13_2]'")
    sys.exit(1)


def mv_correct(predicted: str, expected: str) -> bool:
    """Score predicted vs expected with math-verify. Returns bool."""
    if not predicted or not expected:
        return False
    try:
        gold = mv_parse(f"${expected}$")
        ans = mv_parse(f"${predicted}$")
        if gold and ans:
            return bool(mv_verify_fn(gold, ans))
    except Exception:
        pass
    return False


def rescore_samples(samples: list[dict], expected: str) -> tuple[list[dict], list[bool]]:
    """Re-score a list of {response, predicted, correct, ...} samples. Returns (updated_samples, mv_flags)."""
    mv_flags = []
    updated = []
    for s in samples:
        flag = mv_correct(s.get("predicted", ""), expected)
        mv_flags.append(flag)
        updated.append({**s, "correct": flag})
    return updated, mv_flags


def main():
    parser = argparse.ArgumentParser(description="Re-score math500_results.json with math-verify")
    parser.add_argument(
        "--input",
        default="outputs/math500_results.json",
        help="Path to math500_results.json (output of math500_eval.py)",
    )
    parser.add_argument(
        "--output",
        default="outputs/baseline_math500_mv_rescored.json",
        help="Path to write rescored output",
    )
    args = parser.parse_args()

    input_path = Path(args.input)
    output_path = Path(args.output)

    if not input_path.exists():
        print(f"ERROR: {input_path} not found.")
        print("Run math500_eval.py first to generate it.")
        sys.exit(1)

    print(f"Input:  {input_path}")
    print(f"Output: {output_path}")

    with open(input_path) as f:
        data = json.load(f)

    results = data.get("results", [])
    n_problems = len(results)
    print(f"Problems: {n_problems}")
    print()

    # Per-level and per-subject accumulators
    pass1_level = defaultdict(lambda: {"correct": 0, "total": 0})
    pass8_level = defaultdict(lambda: {"correct": 0, "total": 0})
    pass1_subject = defaultdict(lambda: {"correct": 0, "total": 0})
    pass8_subject = defaultdict(lambda: {"correct": 0, "total": 0})

    pass1_correct_total = 0
    pass8_correct_total = 0
    pass1_inferred_sum = 0.0  # sum of c/n per problem (for inferred pass@1)

    updated_results = []
    for r in results:
        expected = r["expected"]
        level = r["level"]
        subject = r["subject"]

        # Re-score pass1 (greedy)
        pass1_updated, pass1_mv = rescore_samples(r.get("pass1", []), expected)
        pass1_any = any(pass1_mv)
        pass1_correct_total += int(pass1_any)
        pass1_level[level]["total"] += 1
        pass1_level[level]["correct"] += int(pass1_any)
        pass1_subject[subject]["total"] += 1
        pass1_subject[subject]["correct"] += int(pass1_any)

        # Re-score pass8 (sampling)
        pass8_updated, pass8_mv = rescore_samples(r.get("pass8", []), expected)
        pass8_any = any(pass8_mv)
        pass8_correct_total += int(pass8_any)
        pass8_level[level]["total"] += 1
        pass8_level[level]["correct"] += int(pass8_any)
        pass8_subject[subject]["total"] += 1
        pass8_subject[subject]["correct"] += int(pass8_any)

        # Inferred pass@1 from c/n of pass8 samples
        n = len(pass8_mv)
        c = sum(pass8_mv)
        pass1_inferred_sum += (c / n) if n > 0 else 0.0

        updated_results.append({
            **r,
            "pass1": pass1_updated,
            "pass8": pass8_updated,
            # Convenience top-level flags for downstream scripts (e.g. check_reward_parity.py)
            "pass1_mv": pass1_mv,
            "pass8_mv": pass8_mv,
        })

    pass1_acc = pass1_correct_total / n_problems
    pass8_acc = pass8_correct_total / n_problems
    pass1_inferred = pass1_inferred_sum / n_problems

    # Print results
    print("=== RESULTS (math-verify) ===")
    print(f"Greedy pass@1:         {pass1_acc:.2%}  ({pass1_correct_total}/{n_problems})")
    print(f"Pass@8:                {pass8_acc:.2%}  ({pass8_correct_total}/{n_problems})")
    print(f"Inferred pass@1 (c/n): {pass1_inferred:.2%}  (Chen et al. 2021 unbiased estimator)")
    print()
    print("Greedy pass@1 by level:")
    for lvl in sorted(pass1_level.keys()):
        d = pass1_level[lvl]
        print(f"  Level {lvl} (n={d['total']:3d}): {d['correct']/d['total']:.2%}")
    print()
    print("Pass@8 by level:")
    for lvl in sorted(pass8_level.keys()):
        d = pass8_level[lvl]
        print(f"  Level {lvl} (n={d['total']:3d}): {d['correct']/d['total']:.2%}")

    # Build summary
    def level_stats(acc): return {
        str(lvl): {"correct": d["correct"], "total": d["total"], "accuracy": round(d["correct"]/d["total"], 4)}
        for lvl, d in sorted(acc.items())
    }
    def subject_stats(acc): return {
        subj: {"correct": d["correct"], "total": d["total"], "accuracy": round(d["correct"]/d["total"], 4)}
        for subj, d in sorted(acc.items())
    }

    output_data = {
        **{k: v for k, v in data.items() if k != "results"},
        "evaluator": "math-verify[antlr4_13_2]",
        "rescored_by": "scripts/rescore_math500.py",
        "summary": {
            "pass1_greedy": round(pass1_acc, 4),
            "pass8": round(pass8_acc, 4),
            "pass1_inferred_cn": round(pass1_inferred, 4),
            "n_problems": n_problems,
            "pass1_by_level": level_stats(pass1_level),
            "pass8_by_level": level_stats(pass8_level),
            "pass1_by_subject": subject_stats(pass1_subject),
            "pass8_by_subject": subject_stats(pass8_subject),
        },
        "results": updated_results,
    }

    output_path.parent.mkdir(parents=True, exist_ok=True)
    with open(output_path, "w") as f:
        json.dump(output_data, f, indent=2)
    print(f"\nRescored output → {output_path}")


if __name__ == "__main__":
    main()
